<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\YokiFrame.Cli\YokiFrame.Cli.csproj" />
    <ProjectReference Include="..\..\src\YokiFrame.Client\YokiFrame.Client.csproj" />
    <ProjectReference Include="..\..\src\YokiFrame.Protocol\YokiFrame.Protocol.csproj" />
    <ProjectReference Include="..\..\src\YokiFrame.Tooling.Application\YokiFrame.Tooling.Application.csproj" />
  </ItemGroup>

</Project>
