using System.Text.Json.Nodes;
using System.Xml.Linq;
using YokiFrame.Tooling.Application.Models.TableKit;
using YokiFrame.Tooling.Application.Services.TableKit;

namespace YokiFrame.Tooling.Application.Tests.TableKit;

/// <summary>验证 Workbench 编排 TableKit Editor/CodeGenKit 生成跨宿主项目代码。</summary>
public sealed class TableKitCodeGenerationServiceTests
{
    /// <summary>TableKit 专属模板与通用 CodeGenKit 必须分别归属对应 Editor 程序集。</summary>
    [Fact]
    public void SourceGenerationUsesTableKitEditorAndCoreCodeGenKitAssemblies()
    {
        Assert.Equal(
            "YokiFrame.TableKit.Editor",
            typeof(global::YokiFrame.TableKitSourceCodeGenerator).Assembly.GetName().Name);
        Assert.Contains(
            typeof(global::YokiFrame.TableKitSourceCodeGenerator).Assembly.GetReferencedAssemblies(),
            static assembly => string.Equals(assembly.Name, "YokiFrame.Editor", StringComparison.Ordinal));
    }

    /// <summary>Unity 直接生成门面、加载契约和 asmdef，不再产生 manifest 或 Contracts 引用。</summary>
    [Fact]
    public void UnityGenerationWritesCompleteProjectFilesWithoutManifest()
    {
        string root = CreateProjectRoot("unity");
        try
        {
            TableKitOptions options = CreateOptions(root, "Assets/Scripts/TableKit") with
            {
                UseAssemblyDefinition = true,
                GenerateExternalTypeUtil = true
            };
            TableKitContract contract = CreateContract(root, options.OutputCodeDir) with
            {
                ExternalTypeMappings = CreateExternalTypeMappings()
            };
            string outputRoot = contract.OutputCodeDirectory;
            Directory.CreateDirectory(outputRoot);
            File.WriteAllText(Path.Combine(outputRoot, "tablekit.manifest.json"), "{}");
            File.WriteAllText(
                Path.Combine(outputRoot, "ExternalTypeUtil.cs"),
                "// <auto-generated>\n// 由 YokiFrame Workbench TableKit 直接生成，请在 External/ 中放置用户自定义转换代码。\n// </auto-generated>\n");
            File.WriteAllText(Path.Combine(outputRoot, "ProjectConversions.cs"), "// user-owned\n");

            IReadOnlyList<string> files = new TableKitCodeGenerationService().Generate(options, contract);

            string facadePath = Path.Combine(outputRoot, "TableKit.cs");
            string loaderPath = Path.Combine(outputRoot, "ITableDataLoader.cs");
            string asmdefPath = Path.Combine(outputRoot, "YokiFrame.TableKit.asmdef");
            Assert.Contains(facadePath, files);
            Assert.Contains(loaderPath, files);
            Assert.Contains(asmdefPath, files);
            string mapperPath = Path.Combine(outputRoot, "ConfiguredTypeMapper.cs");
            Assert.Contains(mapperPath, files);
            Assert.True(File.Exists(mapperPath));
            Assert.False(File.Exists(Path.Combine(outputRoot, "ExternalTypeUtil.cs")));
            Assert.True(File.Exists(Path.Combine(outputRoot, "ProjectConversions.cs")));
            Assert.False(File.Exists(Path.Combine(outputRoot, "tablekit.manifest.json")));
            Assert.False(File.Exists(Path.Combine(outputRoot, "YokiFrame.TableKit.csproj")));

            string facade = File.ReadAllText(facadePath);
            Assert.DoesNotContain("LubanTables", facade, StringComparison.Ordinal);
            Assert.Contains("namespace YokiFrame", facade, StringComparison.Ordinal);
            Assert.Contains("private static global::Cfg.Tables sTables;", facade, StringComparison.Ordinal);
            Assert.Contains("#if YOKIFRAME_UNITASK_SUPPORT", facade, StringComparison.Ordinal);
            Assert.Contains("using Cysharp.Threading.Tasks;", facade, StringComparison.Ordinal);
            Assert.Contains("public static async UniTask InitAsync", facade, StringComparison.Ordinal);
            Assert.Contains("public static async Task InitAsync", facade, StringComparison.Ordinal);
            Assert.Contains("public static async UniTask<global::Cfg.Tables> LoadAsync", facade, StringComparison.Ordinal);
            Assert.Contains("public static async Task<global::Cfg.Tables> LoadAsync", facade, StringComparison.Ordinal);
            Assert.Contains("public static string RuntimePathPattern => KitSettings.GetString", facade, StringComparison.Ordinal);
            Assert.Contains("public static bool UseRawResourceLoading => KitSettings.GetBool", facade, StringComparison.Ordinal);
            Assert.Contains("? TableDataResourceLoadMode.Raw", facade, StringComparison.Ordinal);
            Assert.Contains(": TableDataResourceLoadMode.Asset", facade, StringComparison.Ordinal);
            Assert.Contains("public static void Init()", facade, StringComparison.Ordinal);
            Assert.Contains("public static void Init(string resourcePathPattern)", facade, StringComparison.Ordinal);
            Assert.Contains("sTables = LoadTables(RuntimePathPattern);", facade, StringComparison.Ordinal);
            Assert.Contains("sTables = await LoadTablesAsync(RuntimePathPattern);", facade, StringComparison.Ordinal);
            Assert.Contains("new ResKitTableDataLoader(sTableNames)", facade, StringComparison.Ordinal);
            Assert.Contains("GetLoader().Load<global::Cfg.Tables>(resourcePathPattern, ResourceLoadMode)", facade, StringComparison.Ordinal);
            Assert.Contains("GetLoader().LoadAsync<global::Cfg.Tables>(resourcePathPattern, ResourceLoadMode)", facade, StringComparison.Ordinal);
            Assert.Contains("\"config\",", facade, StringComparison.Ordinal);
            Assert.Contains("\"item\",", facade, StringComparison.Ordinal);
            Assert.DoesNotContain("TableKit 未设置 ITableDataLoader", facade, StringComparison.Ordinal);
            Assert.DoesNotContain("UseAsyncLoading", facade, StringComparison.Ordinal);
            Assert.DoesNotContain("ConfigureAwait(false)", facade, StringComparison.Ordinal);
            Assert.DoesNotContain("TablesTypeName", facade, StringComparison.Ordinal);
            Assert.DoesNotContain("CodeTarget", facade, StringComparison.Ordinal);
            Assert.DoesNotContain("DataTarget", facade, StringComparison.Ordinal);
            Assert.DoesNotContain("DataExtension", facade, StringComparison.Ordinal);
            Assert.Contains("#if UNITY_EDITOR || (GODOT && TOOLS)", facade, StringComparison.Ordinal);
            Assert.Contains("public static string EditorDataPath", facade, StringComparison.Ordinal);
            Assert.Contains("public static global::Cfg.Tables TablesEditor", facade, StringComparison.Ordinal);
            Assert.Contains("public static void SetEditorDataPath(string path)", facade, StringComparison.Ordinal);
            Assert.Contains("public static void RefreshEditor()", facade, StringComparison.Ordinal);
            Assert.Contains("UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.TextAsset>", facade, StringComparison.Ordinal);
            Assert.DoesNotContain("TableDataLocation", facade, StringComparison.Ordinal);
            Assert.DoesNotContain("LogicalAddress", facade, StringComparison.Ordinal);
            string loader = File.ReadAllText(loaderPath);
            Assert.Contains("namespace YokiFrame", loader, StringComparison.Ordinal);
            Assert.DoesNotContain("namespace YokiFrame.TableKit", loader, StringComparison.Ordinal);
            Assert.Contains("public enum TableDataResourceLoadMode", loader, StringComparison.Ordinal);
            Assert.Contains("public interface ITableDataLoader", loader, StringComparison.Ordinal);
            Assert.Contains("internal sealed class ResKitTableDataLoader", loader, StringComparison.Ordinal);
            Assert.Contains("? ResKit.LoadRaw(path)", loader, StringComparison.Ordinal);
            Assert.Contains("? await ResKit.LoadRawAsync(path)", loader, StringComparison.Ordinal);
            Assert.Contains("ResKit.Load<UnityEngine.TextAsset>(path)", loader, StringComparison.Ordinal);
            Assert.Contains("ResKit.LoadAsync<UnityEngine.TextAsset>(path)", loader, StringComparison.Ordinal);
            Assert.Contains("LoadBinaryTablesAsync<TTables>", loader, StringComparison.Ordinal);
            Assert.Contains(
                "TTables Load<TTables>(string resourcePathPattern, TableDataResourceLoadMode resourceLoadMode)",
                loader,
                StringComparison.Ordinal);
            Assert.Contains(
                "UniTask<TTables> LoadAsync<TTables>(string resourcePathPattern, TableDataResourceLoadMode resourceLoadMode)",
                loader,
                StringComparison.Ordinal);
            Assert.Contains(
                "Task<TTables> LoadAsync<TTables>(string resourcePathPattern, TableDataResourceLoadMode resourceLoadMode)",
                loader,
                StringComparison.Ordinal);
            Assert.DoesNotContain("tablesTypeName", loader, StringComparison.Ordinal);
            Assert.DoesNotContain("ITableDataLocationLoader", loader, StringComparison.Ordinal);
            Assert.DoesNotContain("TableDataLocation", loader, StringComparison.Ordinal);
            string externalTypeUtil = File.ReadAllText(mapperPath);
            Assert.Contains("public static class ConfiguredTypeMapper", externalTypeUtil, StringComparison.Ordinal);
            Assert.Contains("namespace Cfg", externalTypeUtil, StringComparison.Ordinal);
            Assert.Contains("public static UnityEngine.Vector2 CreateVector2(global::Cfg.vector2 value)", externalTypeUtil, StringComparison.Ordinal);
            Assert.Contains("return new UnityEngine.Vector2(value.X, value.Y);", externalTypeUtil, StringComparison.Ordinal);
            Assert.DoesNotContain("using Godot", externalTypeUtil, StringComparison.Ordinal);

            JsonObject asmdef = JsonNode.Parse(File.ReadAllText(asmdefPath))!.AsObject();
            Assert.Equal("YokiFrame.TableKit", asmdef["name"]!.GetValue<string>());
            string[] references = asmdef["references"]!.AsArray().Select(static value => value!.GetValue<string>()).ToArray();
            Assert.Contains("YokiFrame", references);
            Assert.Contains("Luban.Runtime", references);
            Assert.Contains("UniTask", references);
            Assert.DoesNotContain("YokiFrame.TableKit.Contracts", references);
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    /// <summary>显式 topModule 只决定 Luban manager 类型，TableKit 门面和 Loader 契约仍固定在 YokiFrame。</summary>
    [Fact]
    public void UnityGenerationKeepsLubanNamespaceSeparateFromYokiFrameFacade()
    {
        string root = CreateProjectRoot("unity");
        try
        {
            TableKitOptions options = CreateOptions(root, "Assets/Scripts/TableKit");
            TableKitContract contract = CreateContract(root, options.OutputCodeDir) with
            {
                TopModule = "Game.Config"
            };
            WriteManagerSource(contract);

            new TableKitCodeGenerationService().Generate(options, contract);

            string facade = File.ReadAllText(Path.Combine(contract.OutputCodeDirectory, "TableKit.cs"));
            string loader = File.ReadAllText(Path.Combine(contract.OutputCodeDirectory, "ITableDataLoader.cs"));
            Assert.DoesNotContain("LubanTables", facade, StringComparison.Ordinal);
            Assert.Contains("namespace YokiFrame", facade, StringComparison.Ordinal);
            Assert.Contains("private static global::Game.Config.Tables sTables;", facade, StringComparison.Ordinal);
            Assert.Contains("public static global::Game.Config.Tables Tables", facade, StringComparison.Ordinal);
            Assert.Contains("public static global::Game.Config.Tables TablesEditor", facade, StringComparison.Ordinal);
            Assert.DoesNotContain("namespace Game.Config", facade, StringComparison.Ordinal);
            Assert.Contains("namespace YokiFrame", loader, StringComparison.Ordinal);
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    /// <summary>Godot 使用同名 csproj，并由主项目排除源码 glob 后通过 ProjectReference 接入。</summary>
    [Fact]
    public void GodotGenerationWritesUnifiedProjectBoundary()
    {
        string root = CreateProjectRoot("godot");
        try
        {
            TableKitOptions options = CreateOptions(root, "Scripts/TableKit");
            TableKitContract contract = CreateContract(root, options.OutputCodeDir);

            IReadOnlyList<string> files = new TableKitCodeGenerationService().Generate(options, contract);

            string generatedProjectPath = Path.Combine(contract.OutputCodeDirectory, "YokiFrame.TableKit.csproj");
            Assert.Contains(generatedProjectPath, files);
            Assert.False(File.Exists(Path.Combine(contract.OutputCodeDirectory, "YokiFrame.TableKit.asmdef")));
            XDocument generatedProject = XDocument.Load(generatedProjectPath);
            Assert.Equal("Microsoft.NET.Sdk", (string?)generatedProject.Root?.Attribute("Sdk"));
            Assert.Equal("net8.0", Assert.Single(generatedProject.Descendants("TargetFramework")).Value);
            Assert.Equal("YokiFrame.TableKit", Assert.Single(generatedProject.Descendants("AssemblyName")).Value);
            Assert.Contains(generatedProject.Descendants("Reference"), static reference =>
                string.Equals((string?)reference.Attribute("Include"), "Luban.Runtime", StringComparison.Ordinal));
            XElement coreReference = Assert.Single(generatedProject.Descendants("ProjectReference"));
            Assert.Equal(
                "../../addons/yokiframe/package/YokiFrame/Core/Runtime/YokiFrame.csproj",
                ((string?)coreReference.Attribute("Include"))?.Replace('\\', '/'));
            Assert.Equal(
                "YokiFrameToolsBuild=$(YokiFrameToolsBuild)",
                Assert.Single(coreReference.Elements("AdditionalProperties")).Value);

            XDocument mainProject = XDocument.Load(Path.Combine(root, "Game.csproj"));
            XElement ownerGroup = Assert.Single(mainProject.Root!.Elements("ItemGroup"), static group =>
                string.Equals((string?)group.Attribute("Label"), "YokiFrame.TableKit", StringComparison.Ordinal));
            Assert.Equal("Scripts/TableKit/**/*.cs", (string?)Assert.Single(ownerGroup.Elements("Compile")).Attribute("Remove"));
            Assert.Equal(
                "Scripts/TableKit/YokiFrame.TableKit.csproj",
                (string?)Assert.Single(ownerGroup.Elements("ProjectReference")).Attribute("Include"));
            Assert.Contains(
                "YokiFrameToolsBuild=$([System.String]::Copy(';$(DefineConstants);').Contains(';TOOLS;'))",
                Assert.Single(ownerGroup.Descendants("AdditionalProperties")).Value,
                StringComparison.Ordinal);
            Assert.Contains(
                generatedProject.Descendants("DefineConstants"),
                static constants => constants.Value.Contains("GODOT", StringComparison.Ordinal));
            Assert.Contains(
                generatedProject.Descendants("DefineConstants"),
                static constants => constants.Value.Contains("TOOLS", StringComparison.Ordinal));
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    /// <summary>只修改运行时配置不会改写稳定生成源码或更新时间戳。</summary>
    [Fact]
    public void RuntimeConfigurationChangesDoNotRewriteGeneratedSources()
    {
        string root = CreateProjectRoot("unity");
        try
        {
            TableKitOptions options = CreateOptions(root, "Assets/Scripts/TableKit");
            TableKitContract contract = CreateContract(root, options.OutputCodeDir);
            TableKitCodeGenerationService service = new();
            service.Generate(options, contract);
            string facadePath = Path.Combine(contract.OutputCodeDirectory, "TableKit.cs");
            string loaderPath = Path.Combine(contract.OutputCodeDirectory, "ITableDataLoader.cs");
            string facade = File.ReadAllText(facadePath);
            string loader = File.ReadAllText(loaderPath);
            DateTime stableTimestamp = new(2001, 2, 3, 4, 5, 6, DateTimeKind.Utc);
            File.SetLastWriteTimeUtc(facadePath, stableTimestamp);
            File.SetLastWriteTimeUtc(loaderPath, stableTimestamp);

            TableKitOptions changedOptions = options with
            {
                OutputDataDir = "Assets/StreamingAssets/Generated/Tables",
                IsAddressable = true,
                RuntimePathPattern = "external://tables/{0}",
                UseRawResourceLoading = false
            };
            TableKitContract changedContract = contract with
            {
                DataTarget = "json",
                DataExtension = "json",
                IsAddressable = true,
                RuntimePathPattern = "external://tables/{0}",
                OutputDataDirectory = Path.Combine(root, "Assets", "StreamingAssets", "Generated", "Tables")
            };

            service.Generate(changedOptions, changedContract);

            Assert.Equal(facade, File.ReadAllText(facadePath));
            Assert.Equal(loader, File.ReadAllText(loaderPath));
            Assert.Equal(stableTimestamp, File.GetLastWriteTimeUtc(facadePath));
            Assert.Equal(stableTimestamp, File.GetLastWriteTimeUtc(loaderPath));
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    /// <summary>修改 Editor 数据路径时只更新门面的 Editor 默认值，Loader 契约保持稳定。</summary>
    [Fact]
    public void EditorDataPathChangeUpdatesEditorFacadeOnly()
    {
        string root = CreateProjectRoot("unity");
        try
        {
            TableKitOptions options = CreateOptions(root, "Assets/Scripts/TableKit");
            TableKitContract contract = CreateContract(root, options.OutputCodeDir);
            TableKitCodeGenerationService service = new();
            service.Generate(options, contract);
            string facadePath = Path.Combine(contract.OutputCodeDirectory, "TableKit.cs");
            string loaderPath = Path.Combine(contract.OutputCodeDirectory, "ITableDataLoader.cs");
            string originalFacade = File.ReadAllText(facadePath);
            string originalLoader = File.ReadAllText(loaderPath);

            service.Generate(options with { EditorDataPath = "Assets/EditorOnly/Tables" }, contract);

            string changedFacade = File.ReadAllText(facadePath);
            Assert.NotEqual(originalFacade, changedFacade);
            Assert.Contains("Assets/EditorOnly/Tables/", changedFacade, StringComparison.Ordinal);
            Assert.Equal(originalLoader, File.ReadAllText(loaderPath));
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    /// <summary>创建带最小 Unity 或 Godot 识别文件的隔离项目根。</summary>
    /// <param name="kind">项目类型。</param>
    /// <returns>项目根绝对路径。</returns>
    private static string CreateProjectRoot(string kind)
    {
        string root = Path.Combine(Path.GetTempPath(), "yokiframe-tablekit-codegen-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        if (kind == "unity")
        {
            Directory.CreateDirectory(Path.Combine(root, "Assets"));
            Directory.CreateDirectory(Path.Combine(root, "ProjectSettings"));
            File.WriteAllText(Path.Combine(root, "ProjectSettings", "ProjectVersion.txt"), "m_EditorVersion: 2022.3.0f1");
        }
        else
        {
            File.WriteAllText(Path.Combine(root, "project.godot"), "[application]\nconfig/name=\"Game\"\n");
            File.WriteAllText(
                Path.Combine(root, "Game.csproj"),
                "<Project Sdk=\"Godot.NET.Sdk/4.7.0\"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>");
        }
        return root;
    }

    /// <summary>创建代码生成测试使用的页面选项。</summary>
    /// <param name="root">项目根。</param>
    /// <param name="outputCodeDir">项目相对代码根。</param>
    /// <returns>完整 TableKit 选项。</returns>
    private static TableKitOptions CreateOptions(string root, string outputCodeDir)
    {
        return new TableKitOptions
        {
            ProjectRoot = root,
            LubanConfigPath = Path.Combine(root, "Luban", "luban.conf"),
            OutputCodeDir = outputCodeDir,
            EditorDataPath = "Assets/Resources/Art/Table",
            AssemblyName = "YokiFrame.TableKit"
        };
    }

    /// <summary>创建默认 Cfg.Tables Luban 生成契约。</summary>
    /// <param name="root">项目根。</param>
    /// <param name="outputCodeDir">项目相对代码根。</param>
    /// <returns>主 target 契约。</returns>
    private static TableKitContract CreateContract(string root, string outputCodeDir)
    {
        TableKitContract contract = new()
        {
            ConfigPath = Path.Combine(root, "Luban", "luban.conf"),
            TargetName = "client",
            TopModule = "Cfg",
            Manager = "Tables",
            CodeTarget = "cs-bin",
            DataTarget = "bin",
            DataExtension = "bytes",
            IsAddressable = false,
            RuntimePathPattern = "Art/Table/{0}",
            OutputCodeDirectory = Path.GetFullPath(Path.Combine(root, outputCodeDir)),
            OutputDataDirectory = Path.Combine(root, "Data"),
            AssemblyName = "YokiFrame.TableKit"
        };
        WriteManagerSource(contract);
        return contract;
    }

    /// <summary>写入测试使用的最小 Luban manager 原始生成形状。</summary>
    /// <param name="contract">决定命名空间、manager 名和输出根的契约。</param>
    private static void WriteManagerSource(TableKitContract contract)
    {
        string lubanRoot = Path.Combine(contract.OutputCodeDirectory, "Luban");
        Directory.CreateDirectory(lubanRoot);
        string source = "using Luban;\n"
            + "namespace " + contract.TopModule + "\n"
            + "{\n"
            + "    public partial class " + contract.Manager + "\n"
            + "    {\n"
            + "        public " + contract.Manager + "(System.Func<string, ByteBuf> loader)\n"
            + "        {\n"
            + "            _ = loader(\"config\");\n"
            + "            _ = loader(\"item\");\n"
            + "        }\n"
            + "    }\n"
            + "}\n";
        File.WriteAllText(Path.Combine(lubanRoot, contract.Manager + ".cs"), source);
    }

    /// <summary>创建一条模拟 builtin.xml 自定义 constructor 名称的外部类型映射。</summary>
    /// <returns>用于生成 helper 的 mapper 列表。</returns>
    private static IReadOnlyList<TableKitExternalTypeMapping> CreateExternalTypeMappings()
    {
        return new[]
        {
            new TableKitExternalTypeMapping
            {
                SourceTypeName = "global::Cfg.vector2",
                TargetTypeName = "UnityEngine.Vector2",
                HelperNamespace = "Cfg",
                HelperTypeName = "ConfiguredTypeMapper",
                HelperMethodName = "CreateVector2",
                MemberNames = new[] { "X", "Y" }
            }
        };
    }
}
