using System;
using System.Collections.Generic;
using System.Linq;

namespace YokiFrame
{
    /// <summary>使用 CodeGenKit 生成 TableKit 自有的门面、Loader 契约和外部类型 helper。</summary>
    public static partial class TableKitSourceCodeGenerator
    {
        private const string TABLEKIT_NAMESPACE = "YokiFrame";

        /// <summary>生成与门面同程序集的加载契约源码。</summary>
        /// <returns>固定为 C# 9 的 Loader 契约源码。</returns>
        public static string BuildLoaderSource()
        {
            return CodeGenKit.GenerateToString(static root =>
            {
                CodeGenLineBuilder source = CodeGenKit.Lines(root);
                source.AppendLine("// <auto-generated>")
                    .AppendLine("// 由 YokiFrame TableKit 通过 CodeGenKit 生成，请勿手动修改。")
                    .AppendLine("// </auto-generated>")
                    .AppendLine()
                    .AppendLine("using System;")
                    .AppendLine("using System.Collections.Concurrent;")
                    .AppendLine("using System.Collections.Generic;")
                    .AppendLine("using System.IO;")
                    .AppendLine("using System.Reflection;")
                    .AppendLine("#if YOKIFRAME_UNITASK_SUPPORT")
                    .AppendLine("using Cysharp.Threading.Tasks;")
                    .AppendLine("#else")
                    .AppendLine("using System.Threading.Tasks;")
                    .AppendLine("#endif")
                    .AppendLine()
                    .AppendLine("namespace " + TABLEKIT_NAMESPACE)
                    .AppendLine("{");
                AppendLoaderInterfacesSource(source);
                source.AppendLine();
                AppendDefaultResKitLoaderSource(source);
                source.AppendLine("}");
            });
        }

        /// <summary>生成一个 Luban mapper helper 的完整 C# 源码。</summary>
        /// <param name="helperNamespace">helper 所属命名空间。</param>
        /// <param name="helperTypeName">helper 静态类型名。</param>
        /// <param name="mappings">同一 helper 下的 mapper 列表。</param>
        /// <returns>固定为 C# 9 的 helper 源码。</returns>
        public static string BuildExternalTypeHelperSource(
            string helperNamespace,
            string helperTypeName,
            IReadOnlyList<TableKitExternalTypeCodeMapping> mappings)
        {
            string namespaceName = CodeGenKit.RequireQualifiedName(helperNamespace, nameof(helperNamespace));
            string typeName = CodeGenKit.RequireIdentifier(helperTypeName, nameof(helperTypeName));
            if (mappings == null) throw new ArgumentNullException(nameof(mappings));
            return CodeGenKit.GenerateToString(root =>
            {
                CodeGenLineBuilder source = CodeGenKit.Lines(root);
                source.AppendLine("// <auto-generated>")
                    .AppendLine("// Source: Luban bean mapper constructor.")
                    .AppendLine("// 由 YokiFrame TableKit 通过 CodeGenKit 生成，请勿手动修改。")
                    .AppendLine("// </auto-generated>")
                    .AppendLine()
                    .AppendLine("namespace " + namespaceName)
                    .AppendLine("{")
                    .AppendLine("    /// <summary>实现 Luban schema 中声明的外部类型 mapper。</summary>")
                    .AppendLine("    public static class " + typeName)
                    .AppendLine("    {");
                foreach (TableKitExternalTypeCodeMapping mapping in mappings)
                {
                    AppendExternalTypeMapping(source, mapping);
                }
                source.AppendLine("    }")
                    .AppendLine("}");
            });
        }

        /// <summary>通过 CodeGenKit 的事务提交规则写入已经生成的 C# 文本。</summary>
        /// <param name="filePath">目标 C# 文件路径。</param>
        /// <param name="source">完整源码。</param>
        public static void WriteSourceFile(string filePath, string source)
        {
            CodeGenKit.WriteTextToFile(filePath, source);
        }

        /// <summary>写入统一 Loader 接口及其资源模式枚举。</summary>
        /// <param name="source">目标逐行生成器。</param>
        private static void AppendLoaderInterfacesSource(CodeGenLineBuilder source)
        {
            source.AppendLine("    /// <summary>指定项目 Loader 读取配置表资源时使用的资源能力。</summary>")
                .AppendLine("    public enum TableDataResourceLoadMode")
                .AppendLine("    {")
                .AppendLine("        /// <summary>通过宿主普通资源对象读取表数据。</summary>")
                .AppendLine("        Asset,")
                .AppendLine("        /// <summary>通过 ResKit Raw 等原始资源能力读取表数据。</summary>")
                .AppendLine("        Raw")
                .AppendLine("    }")
                .AppendLine()
                .AppendLine("    /// <summary>定义项目侧 TableKit 门面读取 Luban 表管理器的加载契约。</summary>")
                .AppendLine("    public interface ITableDataLoader")
                .AppendLine("    {")
                .AppendLine("        /// <summary>按资源路径模板同步读取并创建表管理器；模板中的 `{0}` 会替换为 Luban 表名。</summary>")
                .AppendLine("        /// <param name=\"resourcePathPattern\">项目资源路径模板；可寻址资源使用 `{0}`。</param>")
                .AppendLine("        /// <param name=\"resourceLoadMode\">项目 Loader 应使用的资源读取能力。</param>")
                .AppendLine("        /// <typeparam name=\"TTables\">当前 Luban target 生成的表管理器类型。</typeparam>")
                .AppendLine("        /// <returns>已创建的表管理器实例。</returns>")
                .AppendLine("        TTables Load<TTables>(string resourcePathPattern, TableDataResourceLoadMode resourceLoadMode) where TTables : class;")
                .AppendLine()
                .AppendLine("        /// <summary>按资源路径模板异步读取并创建表管理器。</summary>")
                .AppendLine("        /// <param name=\"resourcePathPattern\">项目资源路径模板；可寻址资源使用 `{0}`。</param>")
                .AppendLine("        /// <param name=\"resourceLoadMode\">项目 Loader 应使用的资源读取能力。</param>")
                .AppendLine("        /// <typeparam name=\"TTables\">当前 Luban target 生成的表管理器类型。</typeparam>")
                .AppendLine("        /// <returns>异步返回已创建的表管理器实例。</returns>")
                .AppendLine("#if YOKIFRAME_UNITASK_SUPPORT")
                .AppendLine("        UniTask<TTables> LoadAsync<TTables>(string resourcePathPattern, TableDataResourceLoadMode resourceLoadMode) where TTables : class;")
                .AppendLine("#else")
                .AppendLine("        Task<TTables> LoadAsync<TTables>(string resourcePathPattern, TableDataResourceLoadMode resourceLoadMode) where TTables : class;")
                .AppendLine("#endif")
                .AppendLine("    }");
        }

        /// <summary>写入一个 mapper 的方法声明与构造调用。</summary>
        /// <param name="source">目标逐行生成器。</param>
        /// <param name="mapping">外部类型转换契约。</param>
        private static void AppendExternalTypeMapping(
            CodeGenLineBuilder source,
            TableKitExternalTypeCodeMapping mapping)
        {
            if (mapping == null) throw new ArgumentNullException(nameof(mapping));
            string arguments = string.Join(", ", mapping.MemberNames.Select(RequireMemberAccess));
            source.AppendLine("        /// <summary>按 Luban mapper 把 bean 转换为目标类型。</summary>")
                .AppendLine("        /// <param name=\"value\">Luban 生成的 bean 值。</param>")
                .AppendLine("        /// <returns>mapper 声明的目标类型实例。</returns>")
                .AppendLine("        public static " + mapping.TargetTypeName + " " + mapping.HelperMethodName + "(" + mapping.SourceTypeName + " value)")
                .AppendLine("        {")
                .AppendLine("            return new " + mapping.TargetTypeName + "(" + arguments + ");")
                .AppendLine("        }")
                .AppendLine();
        }

        /// <summary>校验 mapper 成员名并转换为 value 成员访问表达式。</summary>
        /// <param name="memberName">Luban bean 成员名。</param>
        /// <returns>可写入生成源码的成员访问表达式。</returns>
        private static string RequireMemberAccess(string memberName)
        {
            return "value." + CodeGenKit.RequireIdentifier(memberName, nameof(memberName));
        }
    }
}
